### ISSUE TITLE
Connect WiFi Access Point

### ISSUE THREAD

**Issue by joelsernamoreno** [GANESH-ICMC/esp32-deauther#7]
Hello!

I have successfully installed ESP32-Deauther, I can see the SSID
But... when I try to connect to the WiFi access point, ESP32 automatically rejects me and I cannot connect properly

Thank you!

**Comment by fnxln** [comment]
Same issue

**Comment by henriquenunez** [comment]
You're not getting it right.
The network generated by the deauther is only a dummy one.
It will send deauth packets to the mac address in the main.cpp file.

Check out the source code please.
