### ISSUE TITLE
Where did ieee80211_raw_frame_sanity_check came from?

### ISSUE THREAD

**Issue by risinek** [GANESH-ICMC/esp32-deauther#9]
Hola,
I'm curious how `ieee80211_raw_frame_sanity_check` function was found? Was it done by decompiling official ESP WiFi libraries similarly to how it was done in [Jeija/esp32-80211-tx](https://github.com/Jeija/esp32-80211-tx) project? I understand how the patch itself works, but I'm interested in details about how it was researched.

**Comment by jaovitubr** [comment]
yes I also want to know where it came from

**Comment by henriquenunez** [comment]
Yep,
Ghidra was used to decompile the firmware, and a call to that function was found and then bypassed.

**Comment by stehlikr** [comment]
Great! Thanks for confirming.

**Comment by risinek** [comment]
Great! Thanks for confirming.
